export default Object.freeze({
    DRAW: "DRAW",
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    JOIN_ERROR: "JOIN_ERROR",
    USER_JOINED_ROOM: "USER_JOINED_ROOM",
    USER_LEFT_ROOM: "USER_LEFT_ROOM",
    REQUEST_CANVAS_DATA: "REQUEST_CANVAS_DATA",
    CANVAS_DATA: "CANVAS_DATA",
});